{% set name = "meshcat-python" %}
{% set version = "0.2.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/meshcat/meshcat-{{ version }}.tar.gz
  sha256: d0e8e655d8f11d50844b9224655275ef08c530651ecc8b1a1d27c53d0cfc683b

build:
  number: 0
  noarch: python
  entry_points:
    - meshcat-server=meshcat.servers.zmqserver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython >=5
    - numpy >=1.14.0
    - pyngrok >=4.1.6
    - python >=3.6
    - pyzmq >=17.0.0
    - tornado >=4.0.0
    - u-msgpack-python >=2.4.1

test:
  imports:
    - meshcat
    - meshcat.servers
  commands:
    - pip check
    - meshcat-server --help
  requires:
    - pip

about:
  home: https://github.com/rdeits/meshcat-python
  summary: WebGL-based visualizer for 3D geometries and scenes
  license: MIT
  license_file:
    - src/meshcat/viewer/LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - jcarpent
